apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
{{- if and (eq .Values.db.type "postgresdb") (eq .Values.webhook.mode "queue") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.webhook.fullname" . }}
  labels:
    {{- include "n8n.webhook.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "n8n.webhook.selectorLabels" . | nindent 4 }}
{{- end }}
