suite: test configmap

templates:
  - configmap.yaml

tests:
  - it: should match snapshot of default values
    release:
      name: n8n
      namespace: n8n
    chart:
      version: 1.0.0
      appVersion: 1.0.0
    asserts:
      - matchSnapshot: { }
