suite: test secret

templates:
  - secret.yaml

tests:
  - it: should match snapshot of default values
    set:
      encryptionKey: my-secret-key
    release:
      name: n8n
      namespace: n8n
    chart:
      version: 1.0.0
      appVersion: 1.0.0
    asserts:
      - matchSnapshot: { }
