suite: test service account

templates:
  - serviceaccount.yaml

tests:
  - it: should be empty when service account is not created
    set:
      serviceAccount.create: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should match snapshot of default values
    set:
      serviceAccount.annotations:
        my-key: my-value
    asserts:
      - equal:
          path: metadata.annotations.my-key
          value: my-value
